#!/usr/bin/env bash
# jreleaser wrapper to inject secrets env

set -TCEeuo pipefail

if [ "${ORGANIZATION_PATH_NAME}" == "" ]; then
  echo "ERROR: ORGANIZATION_PATH_NAME environment variable is not set"
  exit 1
fi

if [ "$PACKAGE_MANAGER" == "maven" ]; then

  # For release
  export JRELEASER_MAVENCENTRAL_USERNAME
  JRELEASER_MAVENCENTRAL_USERNAME=$(pass "$ORGANIZATION_PATH_NAME/sonatype/username")

  export JRELEASER_MAVENCENTRAL_PASSWORD
  JRELEASER_MAVENCENTRAL_PASSWORD=$(pass "$ORGANIZATION_PATH_NAME/sonatype/password")

  # For snapshot
  export JRELEASER_NEXUS2_USERNAME="${JRELEASER_MAVENCENTRAL_USERNAME}"
  export JRELEASER_NEXUS2_PASSWORD="${JRELEASER_MAVENCENTRAL_PASSWORD}"

fi

PASSPHRASE_PATH="$ORGANIZATION_PATH_NAME/gpg/software-signing-key-passphrase"
if ! PASSPHRASE_VALUE=$(pass "$PASSPHRASE_PATH" 2> /dev/null); then
  echo "Note: No gpg passphrase setup. No secret found at the pass path: $PASSPHRASE_PATH"
  PASSPHRASE_VALUE="yolo"
fi
# JReleaser make it mandatory even if it's a command
export JRELEASER_GPG_PASSPHRASE="$PASSPHRASE_VALUE"

# Github
GITHUB_TOKEN_PATH="$ORGANIZATION_PATH_NAME/github/release-token"
if GITHUB_TOKEN_VALUE=$(pass "$GITHUB_TOKEN_PATH"); then
  # for the docker upload
  export JRELEASER_GITHUB_TOKEN="$GITHUB_TOKEN_VALUE"
  export JRELEASER_DOCKER_GHCR_IO_PASSWORD="$GITHUB_TOKEN_VALUE"
else
  echo "Note: No github token found at the pass path: $GITHUB_TOKEN_PATH"
fi

# Standard
# Same as maven (Default to out)
if [ "${JRELEASER_OUTPUT_DIRECTORY:-}" == "" ]; then
  export JRELEASER_OUTPUT_DIRECTORY=target
fi
# execution directory so that we can execute it from anywhere
if [ "$PROJECT_ROOT" != "" ]; then
  export JRELEASER_BASEDIR=$PROJECT_ROOT
fi

# Run
# We select the second in path order
# Why? we may get jreleaser from the project (ie sdk man) and also globally from brew.
# We take the second in order of priority
"$(which -a jreleaser | sed -n '2p')" "$@"
