#!/usr/bin/env bash
# A hook to check for any error in a pom.xml file

set -TCEeuo pipefail

# validate the project is correct and all necessary information is available
# https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html
if ! ./mvnw validate -Dorg.slf4j.simpleLogger.defaultLogLevel=warn; then
  echo "mvn validate command failed"
  exit 1
fi
# Unfortunately, missing version is a warning, not an error
EFFECTIVE_POM=/tmp/effective-pom.xml
# No warning, no error
# We filter out also the lines:
# Downloaded from central:  https://repo.maven.apache
# Downloading from central: https://repo.maven.apache (This second line was a human error. It seems that the term is downloaded, not downloading)
# Grep returns always true
if ! LOG=$(./mvnw help:effective-pom -Dorg.slf4j.simpleLogger.defaultLogLevel=warn -Doutput="$EFFECTIVE_POM" | (grep --invert-match -e "^Download" || true)); then
  printf 'Error mvn effective command failed\n%s' "$LOG"
  exit 1
fi
if [ "$LOG" != "" ]; then
  printf 'Error or warning seen in pom.xml file:\n%s' "$LOG"
  exit 1
fi
